<?php
/**
 * @file
 * slac_policy_demo_pages.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function slac_policy_demo_pages_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 1,
  'title' => '1.2 Desktops',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '171db1de-e76e-4d0a-84fd-49664f4380a4',
  'type' => 'subchapter',
  'language' => 'und',
  'created' => 1401818108,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '0bff9433-1a7d-4d38-9015-4dfacb7a5bd1',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit.&nbsp;</span></p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit. </span></p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_parent_chapter' => array(
    'und' => array(
      0 => array(
        'target_id' => 2,
      ),
    ),
  ),
  'field_subchapter_name' => array(
    'und' => array(
      0 => array(
        'value' => 'Desktops',
        'format' => NULL,
        'safe_value' => 'Desktops',
      ),
    ),
  ),
  'field_subchapter_number' => array(
    'und' => array(
      0 => array(
        'value' => 2,
      ),
    ),
  ),
  'metatags' => array(),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2014-06-03 17:55:08 +0000',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => '2.1 Browser Config',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '21c0f2c5-1f73-487f-9c80-93b318fa32c8',
  'type' => 'subchapter',
  'language' => 'und',
  'created' => 1401818201,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '3a2d4f59-f7ed-429d-ad48-310c55982441',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit.&nbsp;</span><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit.&nbsp;</span></p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit. </span><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit. </span></p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_parent_chapter' => array(
    'und' => array(
      0 => array(
        'target_id' => 3,
      ),
    ),
  ),
  'field_subchapter_name' => array(
    'und' => array(
      0 => array(
        'value' => 'Browser Config',
        'format' => NULL,
        'safe_value' => 'Browser Config',
      ),
    ),
  ),
  'field_subchapter_number' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'metatags' => array(),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2014-06-03 17:56:41 +0000',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => '2.2 Network Config',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'c55226d6-f87b-4bb8-b95f-fe347d89b690',
  'type' => 'subchapter',
  'language' => 'und',
  'created' => 1401818223,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '4cab7bd9-46e6-4df8-b5b9-d1ebf239675d',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit.&nbsp;</span><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit.&nbsp;</span></p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit. </span><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit. </span></p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_parent_chapter' => array(
    'und' => array(
      0 => array(
        'target_id' => 3,
      ),
    ),
  ),
  'field_subchapter_name' => array(
    'und' => array(
      0 => array(
        'value' => 'Network Config',
        'format' => NULL,
        'safe_value' => 'Network Config',
      ),
    ),
  ),
  'field_subchapter_number' => array(
    'und' => array(
      0 => array(
        'value' => 2,
      ),
    ),
  ),
  'metatags' => array(),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2014-06-03 17:57:03 +0000',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => '1.1.1 Obaining a Laptop',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '911a8a57-ed2f-404d-b19e-847b470b6665',
  'type' => 'handbook_page',
  'language' => 'und',
  'created' => 1401818518,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '588903c2-72aa-4bec-94be-cac9a21ad37d',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit.&nbsp;</span><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit.&nbsp;</span></p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit. </span><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit. </span></p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_hbp_applicability' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Everyone</p>
',
        'format' => 'full_html',
        'safe_value' => ' <p>Everyone</p>
 ',
      ),
    ),
  ),
  'field_hbp_attachments' => array(),
  'field_hbp_authority' => array(
    'und' => array(
      0 => array(
        'value' => '<p>CIO</p>
',
        'format' => 'full_html',
        'safe_value' => ' <p>CIO</p>
 ',
      ),
    ),
  ),
  'field_hbp_categories' => array(),
  'field_hbp_current_version' => array(
    'und' => array(
      0 => array(
        'value' => '2014-06-03 00:00:00',
        'timezone' => 'UTC',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
  ),
  'field_hbp_footnote' => array(),
  'field_hbp_hide_bullet_formatting' => array(
    'und' => array(
      0 => array(
        'value' => 0,
      ),
    ),
  ),
  'field_hbp_number' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'field_hbp_original_issue' => array(
    'und' => array(
      0 => array(
        'value' => '2014-06-03 00:00:00',
        'timezone' => 'UTC',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
  ),
  'field_hbp_parent_subchapter' => array(
    'und' => array(
      0 => array(
        'target_id' => 4,
      ),
    ),
  ),
  'field_hbp_related' => array(),
  'field_hbp_subsection' => array(
    'und' => array(
      0 => array(
        'value' => 1,
        'revision_id' => 1,
      ),
      1 => array(
        'value' => 2,
        'revision_id' => 2,
      ),
    ),
  ),
  'field_hbp_suppress_jump_to' => array(
    'und' => array(
      0 => array(
        'value' => 0,
      ),
    ),
  ),
  'field_hbp_title' => array(
    'und' => array(
      0 => array(
        'value' => 'Obaining a Laptop',
        'format' => NULL,
        'safe_value' => 'Obaining a Laptop',
      ),
    ),
  ),
  'field_link_to_cdms' => array(
    'und' => array(
      0 => array(
        'url' => 'http://google.com',
        'title' => 'Documents on CDMS ',
        'attributes' => array(),
      ),
    ),
  ),
  'field_parent_chapter' => array(
    'und' => array(
      0 => array(
        'target_id' => 2,
      ),
    ),
  ),
  'metatags' => array(),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2014-06-03 18:01:58 +0000',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => '1.1 Laptops',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '94d99c96-d2bd-4832-a40c-28d7a80a34d5',
  'type' => 'subchapter',
  'language' => 'und',
  'created' => 1401818082,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '8ebf85a8-de0d-4d88-b09b-094bce360c68',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit.&nbsp;</span><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit.&nbsp;</span></p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit. </span><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit. </span></p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_parent_chapter' => array(
    'und' => array(
      0 => array(
        'target_id' => 2,
      ),
    ),
  ),
  'field_subchapter_name' => array(
    'und' => array(
      0 => array(
        'value' => 'Laptops',
        'format' => NULL,
        'safe_value' => 'Laptops',
      ),
    ),
  ),
  'field_subchapter_number' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'metatags' => array(),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2014-06-03 17:54:42 +0000',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => '1.2.1 Obtaining a Desktop',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '404f9b84-b287-45f9-9d30-1c8a8db30eed',
  'type' => 'handbook_page',
  'language' => 'und',
  'created' => 1401818704,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '97def906-e136-47e1-b6ba-39ae930ffae6',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit.&nbsp;</span><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit.&nbsp;</span></p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit. </span><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit. </span></p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_hbp_applicability' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Everyone</p>
',
        'format' => 'full_html',
        'safe_value' => ' <p>Everyone</p>
 ',
      ),
    ),
  ),
  'field_hbp_attachments' => array(),
  'field_hbp_authority' => array(
    'und' => array(
      0 => array(
        'value' => '<p>CIO</p>
',
        'format' => 'full_html',
        'safe_value' => ' <p>CIO</p>
 ',
      ),
    ),
  ),
  'field_hbp_categories' => array(),
  'field_hbp_current_version' => array(
    'und' => array(
      0 => array(
        'value' => '2014-06-03 00:00:00',
        'timezone' => 'UTC',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
  ),
  'field_hbp_footnote' => array(),
  'field_hbp_hide_bullet_formatting' => array(
    'und' => array(
      0 => array(
        'value' => 0,
      ),
    ),
  ),
  'field_hbp_number' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'field_hbp_original_issue' => array(
    'und' => array(
      0 => array(
        'value' => '2014-06-03 00:00:00',
        'timezone' => 'UTC',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
  ),
  'field_hbp_parent_subchapter' => array(
    'und' => array(
      0 => array(
        'target_id' => 5,
      ),
    ),
  ),
  'field_hbp_related' => array(
    'und' => array(
      0 => array(
        'target_id' => 8,
      ),
    ),
  ),
  'field_hbp_subsection' => array(
    'und' => array(
      0 => array(
        'value' => 3,
        'revision_id' => 3,
      ),
    ),
  ),
  'field_hbp_suppress_jump_to' => array(
    'und' => array(
      0 => array(
        'value' => 0,
      ),
    ),
  ),
  'field_hbp_title' => array(
    'und' => array(
      0 => array(
        'value' => 'Obtaining a Desktop',
        'format' => NULL,
        'safe_value' => 'Obtaining a Desktop',
      ),
    ),
  ),
  'field_link_to_cdms' => array(
    'und' => array(
      0 => array(
        'url' => 'http://www.google.com',
        'title' => 'Link to Doc on CDMS',
        'attributes' => array(),
      ),
    ),
  ),
  'field_parent_chapter' => array(
    'und' => array(
      0 => array(
        'target_id' => 2,
      ),
    ),
  ),
  'metatags' => array(),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2014-06-03 18:05:04 +0000',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => '1. Computing General',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '801ce4e1-772a-446e-83ba-3e6804c2062c',
  'type' => 'chapter',
  'language' => 'und',
  'created' => 1401818007,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'b47533bf-0903-430d-80f4-5b9f2fb2ddc7',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit.&nbsp;</span><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit.&nbsp;</span></p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit. </span><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit. </span></p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_chapter_handbook' => array(
    'und' => array(
      0 => array(
        'target_id' => 1,
      ),
    ),
  ),
  'field_chapter_image' => array(),
  'field_chapter_number' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'field_chapter_title' => array(
    'und' => array(
      0 => array(
        'value' => 'Computing General',
        'format' => NULL,
        'safe_value' => 'Computing General',
      ),
    ),
  ),
  'metatags' => array(),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2014-06-03 17:53:27 +0000',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Cyber ',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '02eeb8e6-dd8c-46e8-846e-cff9a9c8aaab',
  'type' => 'handbook',
  'language' => 'und',
  'created' => 1401817921,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'b53cd035-192b-4a6c-9c48-c663277756e0',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit.&nbsp;</span></p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit. </span></p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'metatags' => array(),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2014-06-03 17:52:01 +0000',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => '2. Security',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '7bd62282-4385-4d52-a166-f4d9a1e47685',
  'type' => 'chapter',
  'language' => 'und',
  'created' => 1401818057,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'd1597e0f-6c61-4b6e-af7f-3097cd8f4bcf',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit.&nbsp;</span></p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p><span style="font-family: arial; font-size: 13px; line-height: normal;">Massa placerat ut auctor in ac placerat tincidunt tortor cursus penatibus? Vut, augue. Pid hac a, parturient egestas! Ac mid. Augue dis et magna odio ut. Tortor, augue lectus nunc, nunc velit lorem tincidunt, mattis turpis pulvinar nisi magna nunc! Turpis ac. Augue lectus, nisi placerat porttitor lundium, aliquet eros vut! Platea odio penatibus purus sit. </span></p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_chapter_handbook' => array(
    'und' => array(
      0 => array(
        'target_id' => 1,
      ),
    ),
  ),
  'field_chapter_image' => array(),
  'field_chapter_number' => array(
    'und' => array(
      0 => array(
        'value' => 2,
      ),
    ),
  ),
  'field_chapter_title' => array(
    'und' => array(
      0 => array(
        'value' => 'Security',
        'format' => NULL,
        'safe_value' => 'Security',
      ),
    ),
  ),
  'metatags' => array(),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2014-06-03 17:54:17 +0000',
);
  return $nodes;
}
