<?php
/**
 * @file
 * slac_policy_demo_pages.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function slac_policy_demo_pages_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 1,
  'title' => '1.2.1 VPN Connections',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '3618133a-e54d-414b-9b6a-68efb88ad1c7',
  'type' => 'handbook_page',
  'language' => 'und',
  'created' => 1401830764,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '072d4a58-ae61-4483-b299-064e98363a76',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p><span style="font-family: arial; font-size: 13px; line-height: normal;">Diam vut pulvinar integer dignissim a, tristique penatibus? Cursus ac elementum rhoncus, arcu elit mid massa lacus, lacus natoque lorem, aliquet a facilisis massa sagittis cras. Ut placerat sed cras, integer cras! Augue, porta nunc hac porta placerat nunc turpis urna magnis? Lacus tortor, porta, sagittis enim sit placerat! Turpis dis massa rhoncus tincidunt? Vut integer!&nbsp;</span></p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p><span style="font-family: arial; font-size: 13px; line-height: normal;">Diam vut pulvinar integer dignissim a, tristique penatibus? Cursus ac elementum rhoncus, arcu elit mid massa lacus, lacus natoque lorem, aliquet a facilisis massa sagittis cras. Ut placerat sed cras, integer cras! Augue, porta nunc hac porta placerat nunc turpis urna magnis? Lacus tortor, porta, sagittis enim sit placerat! Turpis dis massa rhoncus tincidunt? Vut integer! </span></p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_hbp_applicability' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Everyone using a laptop</p>
',
        'format' => 'full_html',
        'safe_value' => ' <p>Everyone using a laptop</p>
 ',
      ),
    ),
  ),
  'field_hbp_attachments' => array(),
  'field_hbp_authority' => array(
    'und' => array(
      0 => array(
        'value' => '<p>OCIO</p>
',
        'format' => 'full_html',
        'safe_value' => ' <p>OCIO</p>
 ',
      ),
    ),
  ),
  'field_hbp_categories' => array(),
  'field_hbp_current_version' => array(
    'und' => array(
      0 => array(
        'value' => '2014-06-03 00:00:00',
        'timezone' => 'UTC',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
  ),
  'field_hbp_footnote' => array(
    'und' => array(
      0 => array(
        'value' => '<p><span style="font-family: arial; font-size: 13px; line-height: normal;">Diam vut pulvinar integer dignissim a, tristique penatibus? Cursus ac elementum rhoncus, arcu elit mid massa lacus, lacus natoque lorem, aliquet a facilisis massa sagittis cras. Ut placerat sed cras, integer cras! Augue, porta nunc hac porta placerat nunc turpis urna magnis? Lacus tortor, porta, sagittis enim sit placerat! Turpis dis massa rhoncus tincidunt? Vut integer!&nbsp;</span></p>
',
        'format' => 'full_html',
        'safe_value' => ' <p><span style="font-family: arial; font-size: 13px; line-height: normal;">Diam vut pulvinar integer dignissim a, tristique penatibus? Cursus ac elementum rhoncus, arcu elit mid massa lacus, lacus natoque lorem, aliquet a facilisis massa sagittis cras. Ut placerat sed cras, integer cras! Augue, porta nunc hac porta placerat nunc turpis urna magnis? Lacus tortor, porta, sagittis enim sit placerat! Turpis dis massa rhoncus tincidunt? Vut integer! </span></p>
 ',
      ),
    ),
  ),
  'field_hbp_hide_bullet_formatting' => array(
    'und' => array(
      0 => array(
        'value' => 0,
      ),
    ),
  ),
  'field_hbp_number' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'field_hbp_original_issue' => array(
    'und' => array(
      0 => array(
        'value' => '2014-06-03 00:00:00',
        'timezone' => 'UTC',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
  ),
  'field_hbp_parent_subchapter' => array(
    'und' => array(
      0 => array(
        'target_id' => 4,
      ),
    ),
  ),
  'field_hbp_related' => array(
    'und' => array(
      0 => array(
        'target_id' => 5,
      ),
    ),
  ),
  'field_hbp_subsection' => array(
    'und' => array(
      0 => array(
        'value' => 5,
        'revision_id' => 5,
      ),
      1 => array(
        'value' => 6,
        'revision_id' => 6,
      ),
    ),
  ),
  'field_hbp_suppress_jump_to' => array(
    'und' => array(
      0 => array(
        'value' => 0,
      ),
    ),
  ),
  'field_hbp_title' => array(
    'und' => array(
      0 => array(
        'value' => 'VPN Connections',
        'format' => NULL,
        'safe_value' => 'VPN Connections',
      ),
    ),
  ),
  'field_link_to_cdms' => array(
    'und' => array(
      0 => array(
        'url' => 'http://google.com',
        'title' => 'This is a link to a document',
        'attributes' => array(),
      ),
    ),
  ),
  'field_parent_chapter' => array(
    'und' => array(
      0 => array(
        'target_id' => 2,
      ),
    ),
  ),
  'metatags' => array(),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2014-06-03 21:26:04 +0000',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => '1.1.1 Browser Security',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'f8b2f5b1-dc59-4b5a-871a-9db6994eff74',
  'type' => 'handbook_page',
  'language' => 'und',
  'created' => 1401830630,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '5eddb85a-0396-4fc9-bb5d-2177be353f53',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p><span style="font-family: arial; font-size: 13px; line-height: normal;">Diam vut pulvinar integer dignissim a, tristique penatibus? Cursus ac elementum rhoncus, arcu elit mid massa lacus, lacus natoque lorem, aliquet a facilisis massa sagittis cras. Ut placerat sed cras, integer cras! Augue, porta nunc hac porta placerat nunc turpis urna magnis? Lacus tortor, porta, sagittis enim sit placerat! Turpis dis massa rhoncus tincidunt? Vut integer!&nbsp;</span><span style="font-family: arial; font-size: 13px; line-height: normal;">Diam vut pulvinar integer dignissim a, tristique penatibus? Cursus ac elementum rhoncus, arcu elit mid massa lacus, lacus natoque lorem, aliquet a facilisis massa sagittis cras. Ut placerat sed cras, integer cras! Augue, porta nunc hac porta placerat nunc turpis urna magnis? Lacus tortor, porta, sagittis enim sit placerat! Turpis dis massa rhoncus tincidunt? Vut integer!&nbsp;</span></p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p><span style="font-family: arial; font-size: 13px; line-height: normal;">Diam vut pulvinar integer dignissim a, tristique penatibus? Cursus ac elementum rhoncus, arcu elit mid massa lacus, lacus natoque lorem, aliquet a facilisis massa sagittis cras. Ut placerat sed cras, integer cras! Augue, porta nunc hac porta placerat nunc turpis urna magnis? Lacus tortor, porta, sagittis enim sit placerat! Turpis dis massa rhoncus tincidunt? Vut integer! </span><span style="font-family: arial; font-size: 13px; line-height: normal;">Diam vut pulvinar integer dignissim a, tristique penatibus? Cursus ac elementum rhoncus, arcu elit mid massa lacus, lacus natoque lorem, aliquet a facilisis massa sagittis cras. Ut placerat sed cras, integer cras! Augue, porta nunc hac porta placerat nunc turpis urna magnis? Lacus tortor, porta, sagittis enim sit placerat! Turpis dis massa rhoncus tincidunt? Vut integer! </span></p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_hbp_applicability' => array(
    'und' => array(
      0 => array(
        'value' => '<p>All users&nbsp;</p>
',
        'format' => 'full_html',
        'safe_value' => ' <p>All users </p>
 ',
      ),
    ),
  ),
  'field_hbp_attachments' => array(),
  'field_hbp_authority' => array(
    'und' => array(
      0 => array(
        'value' => '<p>OCIO</p>
',
        'format' => 'full_html',
        'safe_value' => ' <p>OCIO</p>
 ',
      ),
    ),
  ),
  'field_hbp_categories' => array(),
  'field_hbp_current_version' => array(
    'und' => array(
      0 => array(
        'value' => '2014-06-03 00:00:00',
        'timezone' => 'UTC',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
  ),
  'field_hbp_footnote' => array(
    'und' => array(
      0 => array(
        'value' => '<p><span style="font-family: arial; font-size: 13px; line-height: normal;">Diam vut pulvinar integer dignissim a, tristique penatibus? Cursus ac elementum rhoncus, arcu elit mid massa lacus, lacus natoque lorem, aliquet a facilisis massa sagittis cras. Ut placerat sed cras, integer cras! Augue, porta nunc hac porta placerat nunc turpis urna magnis? Lacus tortor, porta, sagittis enim sit placerat! Turpis dis massa rhoncus tincidunt? Vut integer!&nbsp;</span></p>
',
        'format' => 'full_html',
        'safe_value' => ' <p><span style="font-family: arial; font-size: 13px; line-height: normal;">Diam vut pulvinar integer dignissim a, tristique penatibus? Cursus ac elementum rhoncus, arcu elit mid massa lacus, lacus natoque lorem, aliquet a facilisis massa sagittis cras. Ut placerat sed cras, integer cras! Augue, porta nunc hac porta placerat nunc turpis urna magnis? Lacus tortor, porta, sagittis enim sit placerat! Turpis dis massa rhoncus tincidunt? Vut integer! </span></p>
 ',
      ),
    ),
  ),
  'field_hbp_hide_bullet_formatting' => array(
    'und' => array(
      0 => array(
        'value' => 0,
      ),
    ),
  ),
  'field_hbp_number' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'field_hbp_original_issue' => array(
    'und' => array(
      0 => array(
        'value' => '2014-06-03 00:00:00',
        'timezone' => 'UTC',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
  ),
  'field_hbp_parent_subchapter' => array(
    'und' => array(
      0 => array(
        'target_id' => 3,
      ),
    ),
  ),
  'field_hbp_related' => array(),
  'field_hbp_subsection' => array(
    'und' => array(
      0 => array(
        'value' => 1,
        'revision_id' => 1,
      ),
      1 => array(
        'value' => 2,
        'revision_id' => 2,
      ),
      2 => array(
        'value' => 3,
        'revision_id' => 3,
      ),
      3 => array(
        'value' => 4,
        'revision_id' => 4,
      ),
    ),
  ),
  'field_hbp_suppress_jump_to' => array(
    'und' => array(
      0 => array(
        'value' => 0,
      ),
    ),
  ),
  'field_hbp_title' => array(
    'und' => array(
      0 => array(
        'value' => 'Browser Security',
        'format' => NULL,
        'safe_value' => 'Browser Security',
      ),
    ),
  ),
  'field_link_to_cdms' => array(
    'und' => array(
      0 => array(
        'url' => 'http://www.google.com',
        'title' => 'Link to corresponding CDMS Doc',
        'attributes' => array(),
      ),
    ),
  ),
  'field_parent_chapter' => array(
    'und' => array(
      0 => array(
        'target_id' => 2,
      ),
    ),
  ),
  'metatags' => array(),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2014-06-03 21:23:50 +0000',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => '1. Basic Security',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '5c4d6ea7-f322-4c15-8b10-6e7be4ab0d50',
  'type' => 'chapter',
  'language' => 'und',
  'created' => 1401830435,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '84613a00-96f7-449e-a7c4-ba979845591a',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p><span style="font-family: arial; font-size: 13px; line-height: normal;">Diam vut pulvinar integer dignissim a, tristique penatibus? Cursus ac elementum rhoncus, arcu elit mid massa lacus, lacus natoque lorem, aliquet a facilisis massa sagittis cras. Ut placerat sed cras, integer cras! Augue, porta nunc hac porta placerat nunc turpis urna magnis? Lacus tortor, porta, sagittis enim sit placerat! Turpis dis massa rhoncus tincidunt? Vut integer!&nbsp;</span></p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p><span style="font-family: arial; font-size: 13px; line-height: normal;">Diam vut pulvinar integer dignissim a, tristique penatibus? Cursus ac elementum rhoncus, arcu elit mid massa lacus, lacus natoque lorem, aliquet a facilisis massa sagittis cras. Ut placerat sed cras, integer cras! Augue, porta nunc hac porta placerat nunc turpis urna magnis? Lacus tortor, porta, sagittis enim sit placerat! Turpis dis massa rhoncus tincidunt? Vut integer! </span></p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_chapter_handbook' => array(
    'und' => array(
      0 => array(
        'target_id' => 1,
      ),
    ),
  ),
  'field_chapter_image' => array(),
  'field_chapter_number' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'field_chapter_title' => array(
    'und' => array(
      0 => array(
        'value' => 'Basic Security',
        'format' => NULL,
        'safe_value' => 'Basic Security',
      ),
    ),
  ),
  'metatags' => array(),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2014-06-03 21:20:35 +0000',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Cyber',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '970cee00-aecf-42de-9ca8-1d068c9838fa',
  'type' => 'handbook',
  'language' => 'und',
  'created' => 1401830393,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '9fdef560-668a-4405-b173-40d6b869a10f',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p><span style="font-family: arial; font-size: 13px; line-height: normal;">Diam vut pulvinar integer dignissim a, tristique penatibus? Cursus ac elementum rhoncus, arcu elit mid massa lacus, lacus natoque lorem, aliquet a facilisis massa sagittis cras. Ut placerat sed cras, integer cras! Augue, porta nunc hac porta placerat nunc turpis urna magnis? Lacus tortor, porta, sagittis enim sit placerat! Turpis dis massa rhoncus tincidunt? Vut integer!&nbsp;</span></p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p><span style="font-family: arial; font-size: 13px; line-height: normal;">Diam vut pulvinar integer dignissim a, tristique penatibus? Cursus ac elementum rhoncus, arcu elit mid massa lacus, lacus natoque lorem, aliquet a facilisis massa sagittis cras. Ut placerat sed cras, integer cras! Augue, porta nunc hac porta placerat nunc turpis urna magnis? Lacus tortor, porta, sagittis enim sit placerat! Turpis dis massa rhoncus tincidunt? Vut integer! </span></p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'metatags' => array(),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2014-06-03 21:19:53 +0000',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => '1.1 Securing Desktop',
  'log' => '',
  'status' => 1,
  'comment' => 2,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '5d3f944b-227e-4400-846e-bcacd629ae9d',
  'type' => 'subchapter',
  'language' => 'und',
  'created' => 1401830462,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'e237babb-522e-441f-934f-85f079748bc6',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p><span style="font-family: arial; font-size: 13px; line-height: normal;">Diam vut pulvinar integer dignissim a, tristique penatibus? Cursus ac elementum rhoncus, arcu elit mid massa lacus, lacus natoque lorem, aliquet a facilisis massa sagittis cras. Ut placerat sed cras, integer cras! Augue, porta nunc hac porta placerat nunc turpis urna magnis? Lacus tortor, porta, sagittis enim sit placerat! Turpis dis massa rhoncus tincidunt? Vut integer!&nbsp;</span></p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p><span style="font-family: arial; font-size: 13px; line-height: normal;">Diam vut pulvinar integer dignissim a, tristique penatibus? Cursus ac elementum rhoncus, arcu elit mid massa lacus, lacus natoque lorem, aliquet a facilisis massa sagittis cras. Ut placerat sed cras, integer cras! Augue, porta nunc hac porta placerat nunc turpis urna magnis? Lacus tortor, porta, sagittis enim sit placerat! Turpis dis massa rhoncus tincidunt? Vut integer! </span></p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_parent_chapter' => array(
    'und' => array(
      0 => array(
        'target_id' => 2,
      ),
    ),
  ),
  'field_subchapter_name' => array(
    'und' => array(
      0 => array(
        'value' => 'Securing Desktop',
        'format' => NULL,
        'safe_value' => 'Securing Desktop',
      ),
    ),
  ),
  'field_subchapter_number' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'metatags' => array(),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2014-06-03 21:21:02 +0000',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => '1.2 Securing Laptops',
  'log' => '',
  'status' => 1,
  'comment' => 2,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '1243053b-e88e-4e5d-9e67-d64916f72d8e',
  'type' => 'subchapter',
  'language' => 'und',
  'created' => 1401830487,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'f4bceba9-d1e2-4970-bb77-d12e0c813252',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p><span style="font-family: arial; font-size: 13px; line-height: normal;">Diam vut pulvinar integer dignissim a, tristique penatibus? Cursus ac elementum rhoncus, arcu elit mid massa lacus, lacus natoque lorem, aliquet a facilisis massa sagittis cras. Ut placerat sed cras, integer cras! Augue, porta nunc hac porta placerat nunc turpis urna magnis? Lacus tortor, porta, sagittis enim sit placerat! Turpis dis massa rhoncus tincidunt? Vut integer!&nbsp;</span></p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p><span style="font-family: arial; font-size: 13px; line-height: normal;">Diam vut pulvinar integer dignissim a, tristique penatibus? Cursus ac elementum rhoncus, arcu elit mid massa lacus, lacus natoque lorem, aliquet a facilisis massa sagittis cras. Ut placerat sed cras, integer cras! Augue, porta nunc hac porta placerat nunc turpis urna magnis? Lacus tortor, porta, sagittis enim sit placerat! Turpis dis massa rhoncus tincidunt? Vut integer! </span></p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_parent_chapter' => array(
    'und' => array(
      0 => array(
        'target_id' => 2,
      ),
    ),
  ),
  'field_subchapter_name' => array(
    'und' => array(
      0 => array(
        'value' => 'Securing Laptops',
        'format' => NULL,
        'safe_value' => 'Securing Laptops',
      ),
    ),
  ),
  'field_subchapter_number' => array(
    'und' => array(
      0 => array(
        'value' => 2,
      ),
    ),
  ),
  'metatags' => array(),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2014-06-03 21:21:27 +0000',
);
  return $nodes;
}
