# A sample Gemfile
source "https://rubygems.org"

gem 'compass', '1.0.0.alpha.19'                # Framework built on Sass.
gem 'compass-core'
gem 'susy', '1.0.9'
gem 'sass'
gem 'breakpoint'
gem 'sassy-maps'
gem 'wdm'